### ISSUE TITLE
TypeError: Object [object Object] has no method 'collectionNames'

### ISSUE THREAD

**Issue by bitliner** [powmedia/pow-mongodb-fixtures#19]
It throws the following error:

```
TypeError: Object [object Object] has no method 'collectionNames'
    at getCollectionNames (/home/---/wonderflow/wonderboard/backend/de-en-review-translator/node_modules/pow-mongodb-fixtures/src/index.js:156:28)
    at /home/---/wonderflow/wonderboard/backend/de-en-review-translator/node_modules/pow-mongodb-fixtures/node_modules/async/lib/async.js:494:21
    at /home/---/wonderflow/wonderboard/backend/de-en-review-translator/node_modules/pow-mongodb-fixtures/node_modules/async/lib/async.js:194:13
    at iterate (/home/---/wonderflow/wonderboard/backend/de-en-review-translator/node_modules/pow-mongodb-fixtures/node_modules/async/lib/async.js:118:13)
    at /home/---/wonderflow/wonderboard/backend/de-en-review-translator/node_modules/pow-mongodb-fixtures/node_modules/async/lib/async.js:129:25
    at /home/---/wonderflow/wonderboard/backend/de-en-review-translator/node_modules/pow-mongodb-fixtures/node_modules/async/lib/async.js:196:17
    at /home/---/wonderflow/wonderboard/backend/de-en-review-translator/node_modules/pow-mongodb-fixtures/node_modules/async/lib/async.js:499:34
    at /home/---/wonderflow/wonderboard/backend/de-en-review-translator/node_modules/pow-mongodb-fixtures/src/index.js:146:17
    at /home/---/wonderflow/wonderboard/backend/de-en-review-translator/node_modules/pow-mongodb-fixtures/src/index.js:287:35
    at /home/---/wonderflow/wonderboard/backend/de-en-review-translator/node_modules/pow-mongodb-fixtures/node_modules/mongodb/lib/db.js:200:5

```

The program is the following:

```
var fixtures2 = require('pow-mongodb-fixtures').connect('test', {
  host: 'localhost',
  port: 27017,
/*  user:'test',
  pass:'test'
*/
});

fixtures2.clearAllAndLoad(require('./test/data/data.js'), function(err){
        console.log(err);
})



```

**Comment by pwaller** [comment]
+1 hit this problem.

This would not have happened in the version of mongodb was pinned more carefully.
